### ISSUE TITLE
OverflowError: int too big to convert

### ISSUE THREAD

**Issue by Tvony05** [49jan/hass-ecovent#4]
Hey, maybe you help me out here? Using the Blauberg AHU app everything works just fine.

I've confirmed that the password, port (4000) and IP are correct as the socket doesn't fail as per Logs, unfortunately, I'm getting the "OverflowError: int too big to convert`"

`Error while setting up ecovent platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/ecovent/fan.py", line 77, in async_setup_platform
    fan = EcoVentFan(
  File "/config/custom_components/ecovent/fan.py", line 275, in __init__
    self.update()
  File "/config/custom_components/ecovent/fan.py", line 542, in update
    self.do_func(self.func["read"], request)
  File "/config/custom_components/ecovent/fan.py", line 535, in do_func
    self.parse_response(response)
  File "/config/custom_components/ecovent/fan.py", line 660, in parse_response
    setattr(
  File "/config/custom_components/ecovent/fan.py", line 865, in filter_timer_countdown
    val = int(input, 16).to_bytes(3, "big")
OverflowError: int too big to convert`

Much appreciated. :)

**Comment by 49jan** [comment]
I would like to ask you for some information before I start researching:
1. Which device are you using?
2. What is your current "Time left to filter maintenance" in your mobile app (Basic settings -> Filter)?

**Comment by Tvony05** [comment]
Thanks for the reply. 

1. https://www.rec-indovent.se/en/products/recom-2-a21/ (Blaumberg whitelabel in SE)
2. 47days 8 hours 47 minutes (https://i.ibb.co/Ln76K8N/image.png)

https://www.rec-indovent.se/wp-content/uploads/Teknikermanual_Recom_210505.pdf (SE manual)

**Comment by 49jan** [comment]
I made some corrections that are published in [1.2b](https://github.com/49jan/hass-ecovent/releases/tag/1.2b)

Can you please check if it works and what is displayed in the log?

**Comment by Tvony05** [comment]
Hi, thanks for the effort. 
Unfortunately, still no go.

```
fan:
  - platform: ecovent
    name: Blaumberg
    ip_address: 192.168.68.24
    port: 4000
    device_id: "004400245253XXX"
    password: 11111111
```

```
Logger: homeassistant.components.fan
Source: custom_components/ecovent/fan.py:1148
Integration: Fan ([documentation](https://www.home-assistant.io/integrations/fan), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+fan%22))
First occurred: 09:01:27 (1 occurrences)
Last logged: 09:01:27

Error while setting up ecovent platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/ecovent/fan.py", line 77, in async_setup_platform
    fan = EcoVentFan(
  File "/config/custom_components/ecovent/fan.py", line 275, in __init__
    self.update()
  File "/config/custom_components/ecovent/fan.py", line 542, in update
    self.do_func(self.func["read"], request)
  File "/config/custom_components/ecovent/fan.py", line 535, in do_func
    self.parse_response(response)
  File "/config/custom_components/ecovent/fan.py", line 660, in parse_response
    setattr(
  File "/config/custom_components/ecovent/fan.py", line 1148, in unit_type
    self._unit_type = self.unit_types[val]
KeyError: 256
```

```
Logger: custom_components.ecovent.fan
Source: custom_components/ecovent/fan.py:870
Integration: Eco Heat Recovery Ventilation ([documentation](https://github.com/49jan/hass-ecovent/), [issues](https://github.com/49jan/hass-ecovent/issues))
First occurred: 09:01:27 (1 occurrences)
Last logged: 09:01:27

Cannot parse filter_timer_countdown value '0a112c00': 'int too big to convert'
```

**Comment by 49jan** [comment]
Please update to version 1.3, the problem with unit_type should be fixed.

**Comment by iseneirik** [comment]
This is still an issue, i have submitted a PR with a proposed fix

**Comment by 49jan** [comment]
Thanks for the contribution!

I’ve tested the proposed change, but it seems the current implementation in my setup (using the Blauberg Android app data for reference) works correctly.

The new 4-byte version gives incorrect results — for example, it reports 1028d 33h 0m instead of the correct 4d 4h 33m.
It looks like the payload in this case is actually 3 bytes, where each byte represents minutes, hours, and days respectively.
I’ll therefore keep the 3-byte interpretation, as it matches the data format observed in the app.

Out of curiosity, which device did you test this on?

**Comment by iseneirik** [comment]
The fix in the latest beta-version fixes the issue, thank you for looking into it 👍
