### ISSUE TITLE
AttributeError: 'EcoVentFan' object has no attribute '_device_search'

### ISSUE THREAD

**Issue by jreidel** [49jan/hass-ecovent#5]
Hi,

I just tried the component on my Twinfresh fan, but get an error. I'm not sure if it's not compatible or if this something I can fix. Any idea?

> 2022-09-29 08:36:39.213 ERROR (MainThread) [homeassistant.components.fan] Error while setting up ecovent platform for fan
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/ecovent/fan.py", line 77, in async_setup_platform
fan = EcoVentFan(
File "/config/custom_components/ecovent/fan.py", line 270, in __init__
self._id = self.device_search
File "/config/custom_components/ecovent/fan.py", line 935, in device_search
return self._device_search
AttributeError: 'EcoVentFan' object has no attribute '_device_search'

**Comment by 49jan** [comment]
Can you send your configuration for the fan?

**Comment by jreidel** [comment]
It's very simple, just this in configuration.yaml

```
fan:
  - platform: ecovent
    ip_address: "192.168.86.99"
    name: Tobias
```

The fan is working in various "standard" apps, such as Blauberg Vento and Twinfresh.

**Comment by 49jan** [comment]
It looks like it can't find the device id. Do you see the DeviceID through the apps on your phone? If so, I would suggest that you enter the "device_id" in the config and check if it works for you.

Otherwise, try to enter a random device ID and see if it works for you in this case.

Please reply back with your findings and I'll see if I can do anything on the code to make it easier to use.

**Comment by euinor** [comment]
I had the same error, so I added the device ID as suggested, now I get this error.

```
Logger: homeassistant.components.fan
Source: custom_components/ecovent/fan.py:705
Integration: Fan (documentation, issues)
First occurred: 13:21:30 (2 occurrences)
Last logged: 13:21:30

Error adding entities for domain fan with platform ecovent
Error while setting up ecovent platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 788, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/ecovent/fan.py", line 287, in async_added_to_hass
    self.state,
  File "/config/custom_components/ecovent/fan.py", line 705, in state
    return self._state
AttributeError: 'EcoVentFan' object has no attribute '_state'
```

Configuration.yaml looks like this
```
fan:
  - platform: ecovent
    name: Master Bedroom dMVHR
    ip_address: "192.168.0.22"
    device id: "002E0026424357139"
```
Edit: just noticed I got the IP wrong. I've updated it and restarted but still same error. Fan entity exists now but is on state unavailable.

**Comment by FacePlant101** [comment]
I have the exact same error as this. 

aglehmann's version works though

**Comment by janegilring** [comment]
I initially got this error:

```
2022-12-21 08:22:37.292 ERROR (MainThread) [homeassistant.components.fan] Error while setting up ecovent platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/ecovent/fan.py", line 77, in async_setup_platform
    fan = EcoVentFan(
  File "/config/custom_components/ecovent/fan.py", line 270, in __init__
    self._id = self.device_search
  File "/config/custom_components/ecovent/fan.py", line 935, in device_search
    return self._device_search
AttributeError: 'EcoVentFan' object has no attribute '_device_search'
```

I then added a device id as suggested:
```
fan:
  - platform: ecovent
    name: Basement fan
    ip_address: "10.0.1.154"
    device_id: "85481286"
```

Now the error is:
```
2022-12-21 08:28:38.390 ERROR (MainThread) [homeassistant.components.fan] Error adding entities for domain fan with platform ecovent
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 788, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/ecovent/fan.py", line 287, in async_added_to_hass
    self.state,
  File "/config/custom_components/ecovent/fan.py", line 705, in state
    return self._state
AttributeError: 'EcoVentFan' object has no attribute '_state'
```

**Comment by 49jan** [comment]
Please update to version 1.3, the problem should be fixed.

**Comment by janegilring** [comment]
Thanks, I just upgraded to 1.3.

Now the error changed to:

> File "/config/custom_components/ecovent/fan.py", line 1123, in unit_type  return self._unit_type
> AttributeError: 'EcoVentFan' object has no attribute '_unit_type'

**Comment by janegilring** [comment]
I just tried to setup the integration once more in a new instance of HA, but the error remains the same.

Did anyone get this working?

**Comment by awisur** [comment]
Anyone?

**Comment by 49jan** [comment]
Hi,

A new Beta version (v1.5-beta) has just been released, which most likely resolves the issue you mentioned.
Please update to this version and check if the problem is fixed:
👉 https://github.com/49jan/hass-ecovent/releases/tag/1.5-beta

Thanks for your feedback and for helping improve the integration!
